version: '3.7'

services:

  dj-client:
    container_name: dj-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
